//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobinOperasyonWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPTOR_RBN_TICKET
    {
        public int Id { get; set; }
        public Nullable<int> ParrentId { get; set; }
        public string BackgroundImage { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
