//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobinOperasyonWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBN_EMPTOR_AUTOTICKETCLOSEDScheduler
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> RepeatSchedulerSeconds { get; set; }
        public string SqlCode { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LastStartDate { get; set; }
        public Nullable<int> Process { get; set; }
        public Nullable<int> OneClosedTicketCount { get; set; }
    }
}
