//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobinOperasyonWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBN_EMPTOR_AUTOCLOSEDTICKET
    {
        public int Id { get; set; }
        public Nullable<int> AutoClosedId { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
