//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMTBL_TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRMTBL_TICKET()
        {
            this.CRMTBL_TICKET1 = new HashSet<CRMTBL_TICKET>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> PLANNEDSTARTDATE { get; set; }
        public Nullable<System.DateTime> PLANNEDENDDATE { get; set; }
        public Nullable<int> RESPONSIBLEPOSITIONID { get; set; }
        public Nullable<int> RESPONSIBLEUSERID { get; set; }
        public Nullable<int> TICKETTYPEID { get; set; }
        public Nullable<bool> ISVISIBLETOCUSTOMER { get; set; }
        public Nullable<int> CUSTOMERID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> TICKETSTATUSID { get; set; }
        public Nullable<int> TICKETPRIORITYID { get; set; }
        public Nullable<double> DURATION { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> KNOWLEDGEBASEID { get; set; }
        public Nullable<int> CONTACTCUSTOMERID { get; set; }
        public Nullable<int> CONTRACTID { get; set; }
        public Nullable<int> CONTRACTCONDITIONID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public Nullable<int> RELATEDTICKETID { get; set; }
        public string SOLUTION { get; set; }
        public Nullable<System.DateTime> OPENDATE { get; set; }
        public Nullable<System.DateTime> NOTIFICATIONDATE { get; set; }
        public Nullable<int> CUSTOMERSATISFACTIONID { get; set; }
        public string CUSTOMERREMARKS { get; set; }
        public string C_REFERANCENUMBER { get; set; }
        public string C_FORMNUMBER { get; set; }
        public Nullable<int> C_TICKETSOURCEID { get; set; }
        public Nullable<System.DateTime> C_INTERVENTIONDATE { get; set; }
        public Nullable<System.DateTime> C_SOLUTIONDATE { get; set; }
        public Nullable<bool> C_ISINTERVENTIONTIMEDELAY { get; set; }
        public Nullable<bool> C_ISSOLUTIONTIMEDELAY { get; set; }
        public Nullable<int> C_ANNOUNCERACCOUNTID { get; set; }
        public Nullable<int> C_ANNOUNCERCONTACTID { get; set; }
        public Nullable<int> C_CONCERNEDACCOUNTID { get; set; }
        public Nullable<int> C_CONCERNEDCONTACTID { get; set; }
        public Nullable<int> C_CONTRACTID { get; set; }
        public Nullable<int> C_MAXINTERVENTIONTIME { get; set; }
        public Nullable<int> C_MAXSOLUTIONTIME { get; set; }
        public Nullable<bool> C_ISWAIT { get; set; }
        public Nullable<System.DateTime> C_MAXINTERVENTIONDATE { get; set; }
        public Nullable<System.DateTime> C_MAXSOLUTIONDATE { get; set; }
        public Nullable<System.DateTime> C_BACKCALLDATE { get; set; }
        public Nullable<bool> C_ISUNDERGUARANTEE { get; set; }
        public Nullable<bool> C_ISCONTRACT { get; set; }
        public Nullable<bool> C_ISPAIDFORPART { get; set; }
        public Nullable<bool> C_ISPAIDFORTICKET { get; set; }
        public Nullable<bool> C_ISFREE { get; set; }
        public Nullable<int> C_PROJECTID { get; set; }
        public Nullable<int> C_PROJECTITEMID { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID { get; set; }
        public Nullable<int> CREATE_USER_ID { get; set; }
        public Nullable<int> CREATE_USER_POSITION_ID { get; set; }
        public Nullable<System.DateTime> CREATE_USER_TIME { get; set; }
        public Nullable<int> UPDATE_USER_ID { get; set; }
        public Nullable<int> UPDATE_USER_POSITION_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_USER_TIME { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<int> C_ORGANISATIONID { get; set; }
        public Nullable<int> C_WAITINGREASONID { get; set; }
        public Nullable<int> C_INVENTORYID { get; set; }
        public byte[] ROWSTAMP { get; set; }
        public Nullable<int> CUSTOMERPRIORITYID { get; set; }
        public Nullable<int> C_INTERVENTIONTIME { get; set; }
        public Nullable<int> C_SOLUTIONTIME { get; set; }
        public string CONCERNEDCONTACT { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public int HAS_MAIN_RESPONSIBLE { get; set; }
        public string SIEBELNUMBER { get; set; }
        public Nullable<int> ISFROMPERIODICALSERVICE { get; set; }
        public Nullable<int> C_TICKETSUBAREAID { get; set; }
        public Nullable<int> C_TICKETAREAID { get; set; }
        public Nullable<int> C_INVOICEFIRM { get; set; }
        public string C_INVOICENUMBER { get; set; }
        public string IDDESC { get; set; }
        public Nullable<decimal> C_BILLAMOUNT { get; set; }
        public Nullable<int> C_BILLAMOUNT_CURID { get; set; }
        public string ACCESSORY { get; set; }
        public Nullable<int> C_TICKETSTANDARTLEVELID { get; set; }
        public Nullable<int> C_PLANNEDDAY { get; set; }
        public Nullable<int> C_PLANNEDHOUR { get; set; }
        public Nullable<int> TICKETDISTANCEID { get; set; }
        public Nullable<bool> ISWITHVEHICLE { get; set; }
        public Nullable<bool> ISDONTDOPIDCHECK { get; set; }
        public string SOLUTIONEXPLANATION { get; set; }
        public Nullable<bool> DOAASSET { get; set; }
        public Nullable<bool> GUIDEDTOTHIRDPARTY { get; set; }
        public string SUBRESPONSIBILITY_COMASEPERATED { get; set; }
        public Nullable<int> C_CONCERNEDCONTACTIDWITHEMPREGNO { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID_BENCH { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID_LOGISTICS { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID_PROPOSAL { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID_LEVELONE { get; set; }
        public Nullable<System.DateTime> TICKETLASTACTIVITYDATE { get; set; }
        public Nullable<System.DateTime> APPOINTMENTDATE { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID_INSTALLATION { get; set; }
        public Nullable<System.DateTime> C_MAXINTERVENTIONDATEFROMCONDITION { get; set; }
        public Nullable<System.DateTime> C_MAXSOLUTIONDATEFROMCONDITION { get; set; }
        public Nullable<int> C_INTERVENTIONTIMEDELAY { get; set; }
        public Nullable<int> C_SOLUTIONTIMEDELAY { get; set; }
        public Nullable<bool> HASRESOLVED { get; set; }
        public string BDH_EXTERNALID { get; set; }
        public Nullable<int> TICKETTTNETADDITIONALFIELDID { get; set; }
        public Nullable<int> IDCOPYFORBDHFUNCTIONTABLE { get; set; }
        public Nullable<int> UNCLOSEREASONID { get; set; }
        public string UNCLOSEDETAILS { get; set; }
        public string SUGGESTEDACTION { get; set; }
        public Nullable<int> PROCESSTYPEID { get; set; }
        public string TICKETQUALITYCODE_COMASEPERATED { get; set; }
        public Nullable<bool> ISCABLEDBETWEENSUNKANDROUTER { get; set; }
        public Nullable<double> SUNKCABLELENGTH { get; set; }
        public Nullable<double> TOTALCABLELENGTHBETWEENSUNKANDROUTER { get; set; }
        public Nullable<double> ELECTRICCABLELENGTH { get; set; }
        public string COSTLESSREASON { get; set; }
        public Nullable<int> C_TICKETSTATUSSUBID_CUSTOMER { get; set; }
        public Nullable<System.DateTime> C_TICKETSTATUSSUBID_CUSTOMERDATE { get; set; }
        public string SURVEYINFONOTE { get; set; }
        public Nullable<int> NOSURVEYREASONID { get; set; }
        public Nullable<int> PROBLEMRECORDID { get; set; }
        public Nullable<int> PROBLEMID { get; set; }
        public Nullable<int> TICKETCOSTID { get; set; }
        public Nullable<int> MITOLDID { get; set; }
        public Nullable<bool> ISCLOSED { get; set; }
        public Nullable<int> INTELTEKCIHAZTIPIID { get; set; }
        public string INTELTEKTERMINALNO { get; set; }
        public string C_CUSTOMERSTATUSTEXT { get; set; }
        public string CANCELEXPEND { get; set; }
        public string CANCELEXP { get; set; }
        public Nullable<bool> HASSERVICEFORMREACHEDPHYSICALLY { get; set; }
        public Nullable<int> CONTRACTGROUPGUIDEID { get; set; }
        public Nullable<int> SERVICEVALUE { get; set; }
        public Nullable<int> ProblemImpactID { get; set; }
        public Nullable<int> ProblemProbabilityID { get; set; }
        public Nullable<bool> HasInventoryChange { get; set; }
        public Nullable<int> FORMCONTROLLERID { get; set; }
        public Nullable<System.DateTime> FORMCONTROLDATE { get; set; }
        public string FORMCONTROLNOTES { get; set; }
        public string FORMCONTROLWAITINGACTION { get; set; }
        public Nullable<System.DateTime> PLANNEDDATE_CUSTOMER { get; set; }
        public Nullable<System.DateTime> PLANNEDDATE { get; set; }
        public Nullable<System.DateTime> DEPARTURESTARTTIME { get; set; }
        public string TICKETLOCATIONADDRESS { get; set; }
        public Nullable<int> TICKETLOCATIONCITYID { get; set; }
        public Nullable<int> TICKETLOCATIONDISTRICTID { get; set; }
        public Nullable<int> TICKETLOCATIONCOUNTRYID { get; set; }
        public Nullable<System.DateTime> FAULTRECORDDATE { get; set; }
        public string FAULTRECORDNUMBER { get; set; }
        public string FAULTRECORDEXPLANATION { get; set; }
        public string CIRCUITNUMBER { get; set; }
        public string ISLOCKED { get; set; }
        public Nullable<int> OPTSERVICEWORKTYPE { get; set; }
        public Nullable<int> OPTSERVICESUBJECT { get; set; }
        public Nullable<bool> ISMAJORINCIDENT { get; set; }
        public string MAJORINCIDENTANALYSIS { get; set; }
        public Nullable<int> SERVICEBUSINESSTYPE { get; set; }
        public Nullable<int> SERVICEBUSINESSSUBTYPE { get; set; }
        public Nullable<int> SERVICESOLUTIONTYPE { get; set; }
        public Nullable<int> SERVICESOLUTIONTYPESUB { get; set; }
        public Nullable<int> C_TICKETIMPORTANCEID { get; set; }
        public Nullable<int> C_TICKETIMPACTID { get; set; }
        public Nullable<int> C_SOLUTIONIMPORTANCEID { get; set; }
        public Nullable<int> C_PYPPROJECTID { get; set; }
        public Nullable<int> C_PYPID { get; set; }
        public string TICKET_SERIALNUMBER { get; set; }
        public string ROOTCAUSEANALYSIS { get; set; }
        public string PROBLEMTICKETRELATIONS { get; set; }
        public Nullable<int> RULOREQUESTCOUNT { get; set; }
        public Nullable<int> RULOUSEDCOUNT { get; set; }
        public Nullable<int> POSADDRESID { get; set; }
        public Nullable<int> POSPHONEID { get; set; }
        public Nullable<int> TICKETLEVELCOSTTYPEID { get; set; }
        public Nullable<bool> ISPOLLAPPROVE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMTBL_TICKET> CRMTBL_TICKET1 { get; set; }
        public virtual CRMTBL_TICKET CRMTBL_TICKET2 { get; set; }
    }
}
